/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as IlDottoreRouteImport } from './routes/il-dottore'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as RisultatiRouteImport } from './routes/risultati'
import { Route as TestimonianzeRouteImport } from './routes/testimonianze'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LegaleCookieRouteImport } from './routes/legale.cookie'
import { Route as LegaleDatiSanitariRouteImport } from './routes/legale.dati-sanitari'
import { Route as LegaleDirittiRouteImport } from './routes/legale.diritti'
import { Route as LegalePrivacyRouteImport } from './routes/legale.privacy'
import { Route as LegaleTerminiRouteImport } from './routes/legale.termini'
import { Route as TrattamentiIndexRouteImport } from './routes/trattamenti.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin.agenda'
import { Route as AuthenticatedAdminDocumentiRouteImport } from './routes/_authenticated/admin.documenti'
import { Route as AuthenticatedAdminFerieRouteImport } from './routes/_authenticated/admin.ferie'
import { Route as AuthenticatedAdminImpostazioniRouteImport } from './routes/_authenticated/admin.impostazioni'
import { Route as AuthenticatedAdminLeadRouteImport } from './routes/_authenticated/admin.lead'
import { Route as AuthenticatedAdminPazientiRouteImport } from './routes/_authenticated/admin.pazienti'
import { Route as AuthenticatedAdminRisultatiRouteImport } from './routes/_authenticated/admin.risultati'
import { Route as AuthenticatedAdminTrattamentiRouteImport } from './routes/_authenticated/admin.trattamenti'
import { Route as AuthenticatedAdminTurniRouteImport } from './routes/_authenticated/admin.turni'
import { Route as ApiPublicAppointmentSmsRouteImport } from './routes/api/public/appointment-sms'
import { Route as TrattamentiCategoriaIndexRouteImport } from './routes/trattamenti.$categoria.index'
import { Route as TrattamentiCategoriaSlugRouteImport } from './routes/trattamenti.$categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const IlDottoreRoute = IlDottoreRouteImport.update({
  id: '/il-dottore',
  path: '/il-dottore',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const RisultatiRoute = RisultatiRouteImport.update({
  id: '/risultati',
  path: '/risultati',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonianzeRoute = TestimonianzeRouteImport.update({
  id: '/testimonianze',
  path: '/testimonianze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegaleCookieRoute = LegaleCookieRouteImport.update({
  id: '/legale/cookie',
  path: '/legale/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaleDatiSanitariRoute = LegaleDatiSanitariRouteImport.update({
  id: '/legale/dati-sanitari',
  path: '/legale/dati-sanitari',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaleDirittiRoute = LegaleDirittiRouteImport.update({
  id: '/legale/diritti',
  path: '/legale/diritti',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalePrivacyRoute = LegalePrivacyRouteImport.update({
  id: '/legale/privacy',
  path: '/legale/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegaleTerminiRoute = LegaleTerminiRouteImport.update({
  id: '/legale/termini',
  path: '/legale/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiIndexRoute = TrattamentiIndexRouteImport.update({
  id: '/trattamenti/',
  path: '/trattamenti/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentiRoute =
  AuthenticatedAdminDocumentiRouteImport.update({
    id: '/documenti',
    path: '/documenti',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFerieRoute = AuthenticatedAdminFerieRouteImport.update({
  id: '/ferie',
  path: '/ferie',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImpostazioniRoute =
  AuthenticatedAdminImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadRoute = AuthenticatedAdminLeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPazientiRoute =
  AuthenticatedAdminPazientiRouteImport.update({
    id: '/pazienti',
    path: '/pazienti',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRisultatiRoute =
  AuthenticatedAdminRisultatiRouteImport.update({
    id: '/risultati',
    path: '/risultati',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrattamentiRoute =
  AuthenticatedAdminTrattamentiRouteImport.update({
    id: '/trattamenti',
    path: '/trattamenti',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTurniRoute = AuthenticatedAdminTurniRouteImport.update({
  id: '/turni',
  path: '/turni',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicAppointmentSmsRoute = ApiPublicAppointmentSmsRouteImport.update({
  id: '/api/public/appointment-sms',
  path: '/api/public/appointment-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrattamentiCategoriaIndexRoute =
  TrattamentiCategoriaIndexRouteImport.update({
    id: '/trattamenti/$categoria/',
    path: '/trattamenti/$categoria/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrattamentiCategoriaSlugRoute =
  TrattamentiCategoriaSlugRouteImport.update({
    id: '/trattamenti/$categoria/$slug',
    path: '/trattamenti/$categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contatti': typeof ContattiRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/legale/cookie': typeof LegaleCookieRoute
  '/legale/dati-sanitari': typeof LegaleDatiSanitariRoute
  '/legale/diritti': typeof LegaleDirittiRoute
  '/legale/privacy': typeof LegalePrivacyRoute
  '/legale/termini': typeof LegaleTerminiRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/documenti': typeof AuthenticatedAdminDocumentiRoute
  '/admin/ferie': typeof AuthenticatedAdminFerieRoute
  '/admin/impostazioni': typeof AuthenticatedAdminImpostazioniRoute
  '/admin/lead': typeof AuthenticatedAdminLeadRoute
  '/admin/pazienti': typeof AuthenticatedAdminPazientiRoute
  '/admin/risultati': typeof AuthenticatedAdminRisultatiRoute
  '/admin/trattamenti': typeof AuthenticatedAdminTrattamentiRoute
  '/admin/turni': typeof AuthenticatedAdminTurniRoute
  '/api/public/appointment-sms': typeof ApiPublicAppointmentSmsRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/trattamenti/$categoria/': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contatti': typeof ContattiRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/legale/cookie': typeof LegaleCookieRoute
  '/legale/dati-sanitari': typeof LegaleDatiSanitariRoute
  '/legale/diritti': typeof LegaleDirittiRoute
  '/legale/privacy': typeof LegalePrivacyRoute
  '/legale/termini': typeof LegaleTerminiRoute
  '/trattamenti': typeof TrattamentiIndexRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/documenti': typeof AuthenticatedAdminDocumentiRoute
  '/admin/ferie': typeof AuthenticatedAdminFerieRoute
  '/admin/impostazioni': typeof AuthenticatedAdminImpostazioniRoute
  '/admin/lead': typeof AuthenticatedAdminLeadRoute
  '/admin/pazienti': typeof AuthenticatedAdminPazientiRoute
  '/admin/risultati': typeof AuthenticatedAdminRisultatiRoute
  '/admin/trattamenti': typeof AuthenticatedAdminTrattamentiRoute
  '/admin/turni': typeof AuthenticatedAdminTurniRoute
  '/api/public/appointment-sms': typeof ApiPublicAppointmentSmsRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/trattamenti/$categoria': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contatti': typeof ContattiRoute
  '/il-dottore': typeof IlDottoreRoute
  '/magazine': typeof MagazineRoute
  '/risultati': typeof RisultatiRoute
  '/testimonianze': typeof TestimonianzeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/legale/cookie': typeof LegaleCookieRoute
  '/legale/dati-sanitari': typeof LegaleDatiSanitariRoute
  '/legale/diritti': typeof LegaleDirittiRoute
  '/legale/privacy': typeof LegalePrivacyRoute
  '/legale/termini': typeof LegaleTerminiRoute
  '/trattamenti/': typeof TrattamentiIndexRoute
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/documenti': typeof AuthenticatedAdminDocumentiRoute
  '/_authenticated/admin/ferie': typeof AuthenticatedAdminFerieRoute
  '/_authenticated/admin/impostazioni': typeof AuthenticatedAdminImpostazioniRoute
  '/_authenticated/admin/lead': typeof AuthenticatedAdminLeadRoute
  '/_authenticated/admin/pazienti': typeof AuthenticatedAdminPazientiRoute
  '/_authenticated/admin/risultati': typeof AuthenticatedAdminRisultatiRoute
  '/_authenticated/admin/trattamenti': typeof AuthenticatedAdminTrattamentiRoute
  '/_authenticated/admin/turni': typeof AuthenticatedAdminTurniRoute
  '/api/public/appointment-sms': typeof ApiPublicAppointmentSmsRoute
  '/trattamenti/$categoria/$slug': typeof TrattamentiCategoriaSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/trattamenti/$categoria/': typeof TrattamentiCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contatti'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/admin'
    | '/legale/cookie'
    | '/legale/dati-sanitari'
    | '/legale/diritti'
    | '/legale/privacy'
    | '/legale/termini'
    | '/trattamenti/'
    | '/admin/agenda'
    | '/admin/documenti'
    | '/admin/ferie'
    | '/admin/impostazioni'
    | '/admin/lead'
    | '/admin/pazienti'
    | '/admin/risultati'
    | '/admin/trattamenti'
    | '/admin/turni'
    | '/api/public/appointment-sms'
    | '/trattamenti/$categoria/$slug'
    | '/admin/'
    | '/trattamenti/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contatti'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/legale/cookie'
    | '/legale/dati-sanitari'
    | '/legale/diritti'
    | '/legale/privacy'
    | '/legale/termini'
    | '/trattamenti'
    | '/admin/agenda'
    | '/admin/documenti'
    | '/admin/ferie'
    | '/admin/impostazioni'
    | '/admin/lead'
    | '/admin/pazienti'
    | '/admin/risultati'
    | '/admin/trattamenti'
    | '/admin/turni'
    | '/api/public/appointment-sms'
    | '/trattamenti/$categoria/$slug'
    | '/admin'
    | '/trattamenti/$categoria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contatti'
    | '/il-dottore'
    | '/magazine'
    | '/risultati'
    | '/testimonianze'
    | '/_authenticated/admin'
    | '/legale/cookie'
    | '/legale/dati-sanitari'
    | '/legale/diritti'
    | '/legale/privacy'
    | '/legale/termini'
    | '/trattamenti/'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/documenti'
    | '/_authenticated/admin/ferie'
    | '/_authenticated/admin/impostazioni'
    | '/_authenticated/admin/lead'
    | '/_authenticated/admin/pazienti'
    | '/_authenticated/admin/risultati'
    | '/_authenticated/admin/trattamenti'
    | '/_authenticated/admin/turni'
    | '/api/public/appointment-sms'
    | '/trattamenti/$categoria/$slug'
    | '/_authenticated/admin/'
    | '/trattamenti/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContattiRoute: typeof ContattiRoute
  IlDottoreRoute: typeof IlDottoreRoute
  MagazineRoute: typeof MagazineRoute
  RisultatiRoute: typeof RisultatiRoute
  TestimonianzeRoute: typeof TestimonianzeRoute
  LegaleCookieRoute: typeof LegaleCookieRoute
  LegaleDatiSanitariRoute: typeof LegaleDatiSanitariRoute
  LegaleDirittiRoute: typeof LegaleDirittiRoute
  LegalePrivacyRoute: typeof LegalePrivacyRoute
  LegaleTerminiRoute: typeof LegaleTerminiRoute
  TrattamentiIndexRoute: typeof TrattamentiIndexRoute
  ApiPublicAppointmentSmsRoute: typeof ApiPublicAppointmentSmsRoute
  TrattamentiCategoriaSlugRoute: typeof TrattamentiCategoriaSlugRoute
  TrattamentiCategoriaIndexRoute: typeof TrattamentiCategoriaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/il-dottore': {
      id: '/il-dottore'
      path: '/il-dottore'
      fullPath: '/il-dottore'
      preLoaderRoute: typeof IlDottoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risultati': {
      id: '/risultati'
      path: '/risultati'
      fullPath: '/risultati'
      preLoaderRoute: typeof RisultatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonianze': {
      id: '/testimonianze'
      path: '/testimonianze'
      fullPath: '/testimonianze'
      preLoaderRoute: typeof TestimonianzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legale/cookie': {
      id: '/legale/cookie'
      path: '/legale/cookie'
      fullPath: '/legale/cookie'
      preLoaderRoute: typeof LegaleCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/dati-sanitari': {
      id: '/legale/dati-sanitari'
      path: '/legale/dati-sanitari'
      fullPath: '/legale/dati-sanitari'
      preLoaderRoute: typeof LegaleDatiSanitariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/diritti': {
      id: '/legale/diritti'
      path: '/legale/diritti'
      fullPath: '/legale/diritti'
      preLoaderRoute: typeof LegaleDirittiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/privacy': {
      id: '/legale/privacy'
      path: '/legale/privacy'
      fullPath: '/legale/privacy'
      preLoaderRoute: typeof LegalePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legale/termini': {
      id: '/legale/termini'
      path: '/legale/termini'
      fullPath: '/legale/termini'
      preLoaderRoute: typeof LegaleTerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/': {
      id: '/trattamenti/'
      path: '/trattamenti'
      fullPath: '/trattamenti/'
      preLoaderRoute: typeof TrattamentiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documenti': {
      id: '/_authenticated/admin/documenti'
      path: '/documenti'
      fullPath: '/admin/documenti'
      preLoaderRoute: typeof AuthenticatedAdminDocumentiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ferie': {
      id: '/_authenticated/admin/ferie'
      path: '/ferie'
      fullPath: '/admin/ferie'
      preLoaderRoute: typeof AuthenticatedAdminFerieRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/impostazioni': {
      id: '/_authenticated/admin/impostazioni'
      path: '/impostazioni'
      fullPath: '/admin/impostazioni'
      preLoaderRoute: typeof AuthenticatedAdminImpostazioniRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lead': {
      id: '/_authenticated/admin/lead'
      path: '/lead'
      fullPath: '/admin/lead'
      preLoaderRoute: typeof AuthenticatedAdminLeadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pazienti': {
      id: '/_authenticated/admin/pazienti'
      path: '/pazienti'
      fullPath: '/admin/pazienti'
      preLoaderRoute: typeof AuthenticatedAdminPazientiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/risultati': {
      id: '/_authenticated/admin/risultati'
      path: '/risultati'
      fullPath: '/admin/risultati'
      preLoaderRoute: typeof AuthenticatedAdminRisultatiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trattamenti': {
      id: '/_authenticated/admin/trattamenti'
      path: '/trattamenti'
      fullPath: '/admin/trattamenti'
      preLoaderRoute: typeof AuthenticatedAdminTrattamentiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/turni': {
      id: '/_authenticated/admin/turni'
      path: '/turni'
      fullPath: '/admin/turni'
      preLoaderRoute: typeof AuthenticatedAdminTurniRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/appointment-sms': {
      id: '/api/public/appointment-sms'
      path: '/api/public/appointment-sms'
      fullPath: '/api/public/appointment-sms'
      preLoaderRoute: typeof ApiPublicAppointmentSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$categoria/': {
      id: '/trattamenti/$categoria/'
      path: '/trattamenti/$categoria'
      fullPath: '/trattamenti/$categoria/'
      preLoaderRoute: typeof TrattamentiCategoriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trattamenti/$categoria/$slug': {
      id: '/trattamenti/$categoria/$slug'
      path: '/trattamenti/$categoria/$slug'
      fullPath: '/trattamenti/$categoria/$slug'
      preLoaderRoute: typeof TrattamentiCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminDocumentiRoute: typeof AuthenticatedAdminDocumentiRoute
  AuthenticatedAdminFerieRoute: typeof AuthenticatedAdminFerieRoute
  AuthenticatedAdminImpostazioniRoute: typeof AuthenticatedAdminImpostazioniRoute
  AuthenticatedAdminLeadRoute: typeof AuthenticatedAdminLeadRoute
  AuthenticatedAdminPazientiRoute: typeof AuthenticatedAdminPazientiRoute
  AuthenticatedAdminRisultatiRoute: typeof AuthenticatedAdminRisultatiRoute
  AuthenticatedAdminTrattamentiRoute: typeof AuthenticatedAdminTrattamentiRoute
  AuthenticatedAdminTurniRoute: typeof AuthenticatedAdminTurniRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
  AuthenticatedAdminDocumentiRoute: AuthenticatedAdminDocumentiRoute,
  AuthenticatedAdminFerieRoute: AuthenticatedAdminFerieRoute,
  AuthenticatedAdminImpostazioniRoute: AuthenticatedAdminImpostazioniRoute,
  AuthenticatedAdminLeadRoute: AuthenticatedAdminLeadRoute,
  AuthenticatedAdminPazientiRoute: AuthenticatedAdminPazientiRoute,
  AuthenticatedAdminRisultatiRoute: AuthenticatedAdminRisultatiRoute,
  AuthenticatedAdminTrattamentiRoute: AuthenticatedAdminTrattamentiRoute,
  AuthenticatedAdminTurniRoute: AuthenticatedAdminTurniRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContattiRoute: ContattiRoute,
  IlDottoreRoute: IlDottoreRoute,
  MagazineRoute: MagazineRoute,
  RisultatiRoute: RisultatiRoute,
  TestimonianzeRoute: TestimonianzeRoute,
  LegaleCookieRoute: LegaleCookieRoute,
  LegaleDatiSanitariRoute: LegaleDatiSanitariRoute,
  LegaleDirittiRoute: LegaleDirittiRoute,
  LegalePrivacyRoute: LegalePrivacyRoute,
  LegaleTerminiRoute: LegaleTerminiRoute,
  TrattamentiIndexRoute: TrattamentiIndexRoute,
  ApiPublicAppointmentSmsRoute: ApiPublicAppointmentSmsRoute,
  TrattamentiCategoriaSlugRoute: TrattamentiCategoriaSlugRoute,
  TrattamentiCategoriaIndexRoute: TrattamentiCategoriaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
